# -*- coding: utf-8 -*-
"""Copy of Logistic Regression

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10aNcN7OYrIaEr951idhTQXz8pW9fxSmP

# Logistic Regression

## Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing the dataset"""

dataset=pd.read_csv("breast_cancer.csv")
X=dataset.iloc[ : ,1:-1].values
Y=dataset.iloc[ : ,-1].values

print(X)

print(Y)

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

print(X_train)

print(X_test)

print(Y_train)

print(Y_test)

"""## Training the Logistic Regression model on the Training set"""

from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(X_train,Y_train)

"""## Predicting the Test set results"""

Y_pred=classifier.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1),Y_test.reshape(len(Y_test),1)),1))

"""## Making the Confusion Matrix"""

from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(Y_test,Y_pred)
print(cm)
print(accuracy_score(Y_test,Y_pred))

"""## Computing the accuracy with k-Fold Cross Validation"""

from sklearn.model_selection import cross_val_score
accuracies=cross_val_score(estimator=classifier,X=X_train,y=Y_train,cv=10)
print("Accuracy= {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation= {:.2f} %".format(accuracies.std()*100))